exports.timers = {
    SHOW_PRE_DECISION_TIME: 1,
    SHOW_DECISION_TIME: 3,
    SHOW_CORRECT_ANSWER_TIME: 2,
    SHOW_SCOREBOARD_PRE_UPDATE_TIME: 1,
    SHOW_SCOREBOARD_UPDATE_TIME: 3,

    BUZZ_IN_TIMEOUT: 5,
    ANSWER_TIMEOUT: 10
};
