exports.timers = {
    SHOW_CLUE_ANIMATION: 1,
    SHOW_DAILY_DOUBLE_ANIMATION: 5,

    SHOW_PRE_DECISION_TIME: 1,
    SHOW_CORRECT_ANSWER_TIME: 2,
    SHOW_SCOREBOARD_PRE_UPDATE_TIME: 1,
    SHOW_SCOREBOARD_UPDATE_TIME: 3,

    WAGER_TIMEOUT: 10,
    BUZZ_IN_TIMEOUT: 5,
    ANSWER_TIMEOUT: 10
};
